run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-dirs:
    - docs
    - tmp
    - bin

skip-dirs:
  - docs
  - tmp
  - bin
