-- Urutan reverse FK
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS no_transaksi_seq CASCADE;
DROP TABLE IF EXISTS stock_alerts CASCADE;
DROP TABLE IF EXISTS price_change_logs CASCADE;
DROP TABLE IF EXISTS riwayat_pembayaran CASCADE;
DROP TABLE IF EXISTS transaksi_detail_promo CASCADE;
DROP TABLE IF EXISTS transaksi_detail CASCADE;
DROP TABLE IF EXISTS transaksi_penjualan CASCADE;
DROP TABLE IF EXISTS promos CASCADE;
DROP TABLE IF EXISTS stock_movements CASCADE;
DROP TABLE IF EXISTS barang_masuk CASCADE;
DROP TABLE IF EXISTS pelanggan CASCADE;
DROP TABLE IF EXISTS barang CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
