-- Skema domain PKB Web (15 tabel) — lihat docs/03-model-data.md

CREATE TABLE users (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMP NULL,
    password        VARCHAR(255) NOT NULL,
    role            ENUM('super_admin','admin','afiliasi','sales') NOT NULL DEFAULT 'sales',
    no_hp           VARCHAR(30) NULL,
    no_ktp          VARCHAR(32) NULL,
    alamat          TEXT NULL,
    jenis_kelamin   ENUM('L','P') NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NULL,
    updated_at      TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_email (email),
    UNIQUE KEY uq_users_no_ktp (no_ktp),
    KEY idx_users_role_active (role, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE refresh_tokens (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id     BIGINT UNSIGNED NOT NULL,
    token_hash  CHAR(64) NOT NULL,
    expires_at  DATETIME NOT NULL,
    revoked_at  DATETIME NULL,
    user_agent  VARCHAR(255) NULL,
    ip_address  VARCHAR(45) NULL,
    created_at  TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_refresh_token_hash (token_hash),
    KEY idx_refresh_user_expired (user_id, expires_at),
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE barang (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    kode_barang     VARCHAR(64) NOT NULL,
    nama_item       VARCHAR(255) NOT NULL,
    brand           VARCHAR(100) NOT NULL,
    satuan          VARCHAR(20) NOT NULL DEFAULT 'PCS',
    stok_tersedia   INT NOT NULL DEFAULT 0,
    min_stock       INT NOT NULL DEFAULT 0,
    reorder_point   INT NOT NULL DEFAULT 0,
    metode_alokasi  ENUM('FEFO','FIFO') NOT NULL DEFAULT 'FEFO',
    expiry_alert_days INT NOT NULL DEFAULT 30,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      TIMESTAMP NULL,
    updated_at      TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_barang_kode (kode_barang),
    KEY idx_barang_brand (brand),
    KEY idx_barang_active_stok (is_active, stok_tersedia),
    KEY idx_barang_nama (nama_item)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE pelanggan (
    id                        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    kode_pelanggan            VARCHAR(32) NOT NULL,
    nama_pelanggan            VARCHAR(255) NOT NULL,
    tgl_registrasi            DATE NOT NULL,
    phone                     VARCHAR(30) NOT NULL,
    npwp_nik                  VARCHAR(32) NULL,
    nama_pemilik_npwp_nik     VARCHAR(255) NULL,
    alamat_npwp_nik           TEXT NULL,
    territory                 VARCHAR(100) NOT NULL,
    distrik                   VARCHAR(100) NOT NULL,
    alamat_toko               TEXT NOT NULL,
    rt_rw                     VARCHAR(20) NULL,
    provinsi                  VARCHAR(100) NOT NULL,
    kabupaten                 VARCHAR(100) NOT NULL,
    kecamatan                 VARCHAR(100) NOT NULL,
    kelurahan                 VARCHAR(100) NOT NULL,
    kode_pos                  VARCHAR(10) NULL,
    channel_outlet            ENUM('Modern Trade','Modern Trade Independent','General Trade','General Trade Kosmetik','Sub Agen') NOT NULL,
    alamat_pengantaran_barang TEXT NULL,
    jenis_bangunan            VARCHAR(50) NULL,
    status_bangunan           VARCHAR(50) NULL,
    nominal_pengambilan_pertama DECIMAL(15,2) NOT NULL DEFAULT 0,
    estimasi_batas_kredit     DECIMAL(15,2) NOT NULL DEFAULT 0,
    is_active                 TINYINT(1) NOT NULL DEFAULT 1,
    created_at                TIMESTAMP NULL,
    updated_at                TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_pelanggan_kode (kode_pelanggan),
    KEY idx_pelanggan_channel (channel_outlet),
    KEY idx_pelanggan_wilayah (territory, distrik),
    KEY idx_pelanggan_nama (nama_pelanggan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE barang_masuk (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    barang_id         BIGINT UNSIGNED NOT NULL,
    no_faktur         VARCHAR(100) NOT NULL,
    no_batch          VARCHAR(100) NOT NULL,
    exp               DATE NOT NULL,
    tanggal_masuk     DATE NOT NULL,
    qty               INT NOT NULL,
    harga             DECIMAL(15,2) NOT NULL,
    disc_hpp_1        DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc_hpp_2        DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc_hpp_3        DECIMAL(5,2) NOT NULL DEFAULT 0,
    hpp               DECIMAL(15,2) NOT NULL DEFAULT 0,
    hpp_dengan_ppn    DECIMAL(15,2) NOT NULL DEFAULT 0,
    markup_mt_type    ENUM('percent','value') NOT NULL DEFAULT 'percent',
    markup_mt_amount  DECIMAL(15,2) NOT NULL DEFAULT 0,
    markup_gt_type    ENUM('percent','value') NOT NULL DEFAULT 'percent',
    markup_gt_amount  DECIMAL(15,2) NOT NULL DEFAULT 0,
    harga_mt          DECIMAL(15,2) NOT NULL DEFAULT 0,
    harga_gt          DECIMAL(15,2) NOT NULL DEFAULT 0,
    aging_month       INT NOT NULL DEFAULT 0,
    created_by        BIGINT UNSIGNED NULL,
    created_at        TIMESTAMP NULL,
    updated_at        TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_bm_batch (barang_id, no_batch, no_faktur),
    KEY idx_bm_barang_exp (barang_id, exp),
    KEY idx_bm_tanggal (tanggal_masuk),
    KEY idx_bm_faktur (no_faktur),
    CONSTRAINT fk_bm_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_bm_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_bm_qty CHECK (qty > 0),
    CONSTRAINT chk_bm_disc CHECK (
        disc_hpp_1 BETWEEN 0 AND 100 AND
        disc_hpp_2 BETWEEN 0 AND 100 AND
        disc_hpp_3 BETWEEN 0 AND 100
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE stock_movements (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    barang_id         BIGINT UNSIGNED NOT NULL,
    barang_masuk_id   BIGINT UNSIGNED NULL,
    movement_type     ENUM('PENERIMAAN','PENJUALAN','PEMBATALAN','PENYESUAIAN','OPNAME') NOT NULL,
    qty               INT NOT NULL,
    saldo_setelah     INT NOT NULL,
    reference_type    VARCHAR(50) NULL,
    reference_id      BIGINT UNSIGNED NULL,
    reference_no      VARCHAR(100) NULL,
    keterangan        TEXT NULL,
    created_by        BIGINT UNSIGNED NULL,
    created_at        DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_sm_barang_created (barang_id, created_at),
    KEY idx_sm_batch (barang_masuk_id),
    KEY idx_sm_reference (reference_type, reference_id),
    KEY idx_sm_type_created (movement_type, created_at),
    CONSTRAINT fk_sm_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sm_batch FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sm_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_sm_qty CHECK (qty <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE promos (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    kode_promo          VARCHAR(64) NOT NULL,
    nama_promo          VARCHAR(255) NOT NULL,
    deskripsi           TEXT NULL,
    tipe_promo          ENUM('buy_x_get_y','bonus_qty','percentage_discount','fixed_discount') NOT NULL,
    buy_qty             INT NULL,
    get_qty             INT NULL,
    bonus_qty           INT NOT NULL DEFAULT 0,
    discount_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    discount_amount     DECIMAL(15,2) NOT NULL DEFAULT 0,
    min_qty             INT NOT NULL DEFAULT 1,
    min_amount          DECIMAL(15,2) NOT NULL DEFAULT 0,
    max_applications    INT NULL,
    kode_barang         VARCHAR(64) NULL,
    tanggal_mulai       DATE NOT NULL,
    tanggal_berakhir    DATE NOT NULL,
    is_active           TINYINT(1) NOT NULL DEFAULT 1,
    syarat_ketentuan    TEXT NULL,
    created_by          BIGINT UNSIGNED NULL,
    created_at          TIMESTAMP NULL,
    updated_at          TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_promo_kode (kode_promo),
    KEY idx_promo_aktif (is_active, tanggal_mulai, tanggal_berakhir),
    KEY idx_promo_barang (kode_barang),
    CONSTRAINT fk_promo_barang FOREIGN KEY (kode_barang) REFERENCES barang(kode_barang) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_promo_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_promo_periode CHECK (tanggal_berakhir >= tanggal_mulai),
    CONSTRAINT chk_promo_bxgy CHECK (
        tipe_promo <> 'buy_x_get_y'
        OR (buy_qty IS NOT NULL AND buy_qty > 0 AND get_qty IS NOT NULL AND get_qty > 0)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transaksi_penjualan (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    no_transaksi      VARCHAR(32) NULL,
    tanggal           DATE NOT NULL,
    periode           CHAR(7) NOT NULL,
    kode_pelanggan    VARCHAR(32) NOT NULL,
    nama_pelanggan    VARCHAR(255) NOT NULL,
    alamat            TEXT NOT NULL,
    channel_outlet    VARCHAR(50) NOT NULL,
    area              VARCHAR(100) NOT NULL,
    is_multi_item     TINYINT(1) NOT NULL DEFAULT 1,
    disc1_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc2_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc3_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    ppn_persen        DECIMAL(5,2) NOT NULL DEFAULT 11,
    total             DECIMAL(15,2) NOT NULL DEFAULT 0,
    ppn_nominal       DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_akhir       DECIMAL(15,2) NOT NULL DEFAULT 0,
    jumlah_item       INT NOT NULL DEFAULT 0,
    total_qty_ditagih INT NOT NULL DEFAULT 0,
    total_qty_keluar  INT NOT NULL DEFAULT 0,
    status_approval   ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    approved_at       DATETIME NULL,
    approved_by       BIGINT UNSIGNED NULL,
    approval_notes    TEXT NULL,
    fulfillment_status ENUM('awaiting_approval','full','partial','backorder','stock_shortage') NOT NULL DEFAULT 'awaiting_approval',
    qty_fulfilled     INT NOT NULL DEFAULT 0,
    qty_backorder     INT NOT NULL DEFAULT 0,
    stock_notes       TEXT NULL,
    status_pembayaran ENUM('lunas','hutang','sebagian') NOT NULL DEFAULT 'hutang',
    jumlah_dibayar    DECIMAL(15,2) NOT NULL DEFAULT 0,
    sisa_hutang       DECIMAL(15,2) NOT NULL DEFAULT 0,
    tanggal_jatuh_tempo DATE NULL,
    tanggal_pembayaran_terakhir DATETIME NULL,
    keterangan_pembayaran TEXT NULL,
    faktur_dicetak_at DATETIME NULL,
    faktur_dicetak_by BIGINT UNSIGNED NULL,
    sales_id          BIGINT UNSIGNED NULL,
    created_at        TIMESTAMP NULL,
    updated_at        TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_tp_no_transaksi (no_transaksi),
    KEY idx_tp_status_tanggal (status_approval, tanggal),
    KEY idx_tp_pelanggan (kode_pelanggan),
    KEY idx_tp_sales_tanggal (sales_id, tanggal),
    KEY idx_tp_bayar (status_pembayaran, tanggal_jatuh_tempo),
    KEY idx_tp_periode (periode),
    KEY idx_tp_channel (channel_outlet),
    CONSTRAINT fk_tp_pelanggan FOREIGN KEY (kode_pelanggan) REFERENCES pelanggan(kode_pelanggan) ON UPDATE CASCADE,
    CONSTRAINT fk_tp_sales FOREIGN KEY (sales_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tp_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_tp_bayar CHECK (
        ABS(jumlah_dibayar + sisa_hutang - total_akhir) < 0.01
    ),
    CONSTRAINT chk_tp_approved CHECK (
        (status_approval = 'approved' AND no_transaksi IS NOT NULL AND approved_at IS NOT NULL)
        OR status_approval <> 'approved'
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transaksi_detail (
    id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transaksi_penjualan_id BIGINT UNSIGNED NOT NULL,
    urutan                SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    kode_item             VARCHAR(64) NOT NULL,
    nama_item             VARCHAR(255) NOT NULL,
    satuan                VARCHAR(20) NOT NULL,
    barang_masuk_id       BIGINT UNSIGNED NULL,
    batch_number          VARCHAR(100) NULL,
    expiry_date           DATE NULL,
    qty                   INT NOT NULL,
    qty_promo             INT NOT NULL DEFAULT 0,
    total_qty_keluar      INT NOT NULL DEFAULT 0,
    harga                 DECIMAL(15,2) NOT NULL,
    subtotal              DECIMAL(15,2) NOT NULL,
    disc1_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc2_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc3_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    total_after_disc      DECIMAL(15,2) NOT NULL,
    hpp_snapshot          DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at            TIMESTAMP NULL,
    updated_at            TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_td_urutan (transaksi_penjualan_id, urutan),
    KEY idx_td_transaksi (transaksi_penjualan_id),
    KEY idx_td_item (kode_item),
    KEY idx_td_batch (barang_masuk_id),
    CONSTRAINT fk_td_transaksi FOREIGN KEY (transaksi_penjualan_id) REFERENCES transaksi_penjualan(id) ON DELETE CASCADE,
    CONSTRAINT fk_td_barang FOREIGN KEY (kode_item) REFERENCES barang(kode_barang) ON UPDATE CASCADE,
    CONSTRAINT fk_td_batch FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE RESTRICT,
    CONSTRAINT chk_td_qty CHECK (qty > 0 AND qty_promo >= 0),
    CONSTRAINT chk_td_qty_keluar CHECK (total_qty_keluar = qty + qty_promo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE transaksi_detail_promo (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transaksi_detail_id BIGINT UNSIGNED NOT NULL,
    promo_id            BIGINT UNSIGNED NOT NULL,
    kode_promo          VARCHAR(64) NOT NULL,
    nama_promo          VARCHAR(255) NOT NULL,
    tipe_promo          ENUM('buy_x_get_y','bonus_qty','percentage_discount','fixed_discount') NOT NULL,
    qty_bonus           INT NOT NULL DEFAULT 0,
    nilai_diskon        DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY idx_tdp_detail (transaksi_detail_id),
    KEY idx_tdp_promo (promo_id),
    CONSTRAINT fk_tdp_detail FOREIGN KEY (transaksi_detail_id) REFERENCES transaksi_detail(id) ON DELETE CASCADE,
    CONSTRAINT fk_tdp_promo FOREIGN KEY (promo_id) REFERENCES promos(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE riwayat_pembayaran (
    id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transaksi_penjualan_id BIGINT UNSIGNED NOT NULL,
    old_jumlah_dibayar DECIMAL(15,2) NOT NULL DEFAULT 0,
    new_jumlah_dibayar DECIMAL(15,2) NOT NULL DEFAULT 0,
    old_sisa_hutang    DECIMAL(15,2) NOT NULL DEFAULT 0,
    new_sisa_hutang    DECIMAL(15,2) NOT NULL DEFAULT 0,
    old_status         ENUM('lunas','hutang','sebagian') NULL,
    new_status         ENUM('lunas','hutang','sebagian') NULL,
    nominal_pembayaran DECIMAL(15,2) NOT NULL DEFAULT 0,
    metode_pembayaran  VARCHAR(50) NULL,
    tanggal_pembayaran DATE NULL,
    keterangan         TEXT NULL,
    changed_by         BIGINT UNSIGNED NULL,
    changed_at         DATETIME(3) NOT NULL,
    created_at         TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY idx_rp_transaksi (transaksi_penjualan_id, changed_at),
    KEY idx_rp_tanggal (tanggal_pembayaran),
    CONSTRAINT fk_rp_transaksi FOREIGN KEY (transaksi_penjualan_id) REFERENCES transaksi_penjualan(id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_user FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE price_change_logs (
    id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    barang_masuk_id   BIGINT UNSIGNED NOT NULL,
    barang_id         BIGINT UNSIGNED NOT NULL,
    bulk_operation_id CHAR(36) NOT NULL,
    old_harga         DECIMAL(15,2) NULL,
    old_disc_hpp_1    DECIMAL(5,2) NULL,
    old_disc_hpp_2    DECIMAL(5,2) NULL,
    old_disc_hpp_3    DECIMAL(5,2) NULL,
    old_markup_mt_type   ENUM('percent','value') NULL,
    old_markup_mt_amount DECIMAL(15,2) NULL,
    old_markup_gt_type   ENUM('percent','value') NULL,
    old_markup_gt_amount DECIMAL(15,2) NULL,
    old_harga_mt      DECIMAL(15,2) NULL,
    old_harga_gt      DECIMAL(15,2) NULL,
    old_hpp           DECIMAL(15,2) NULL,
    new_harga         DECIMAL(15,2) NULL,
    new_disc_hpp_1    DECIMAL(5,2) NULL,
    new_disc_hpp_2    DECIMAL(5,2) NULL,
    new_disc_hpp_3    DECIMAL(5,2) NULL,
    new_markup_mt_type   ENUM('percent','value') NULL,
    new_markup_mt_amount DECIMAL(15,2) NULL,
    new_markup_gt_type   ENUM('percent','value') NULL,
    new_markup_gt_amount DECIMAL(15,2) NULL,
    new_harga_mt      DECIMAL(15,2) NULL,
    new_harga_gt      DECIMAL(15,2) NULL,
    new_hpp           DECIMAL(15,2) NULL,
    keterangan        TEXT NULL,
    changed_by        BIGINT UNSIGNED NULL,
    changed_at        DATETIME(3) NOT NULL,
    created_at        TIMESTAMP NULL,
    PRIMARY KEY (id),
    KEY idx_pcl_barang (barang_id, changed_at),
    KEY idx_pcl_bulk (bulk_operation_id),
    KEY idx_pcl_bm (barang_masuk_id),
    CONSTRAINT fk_pcl_bm FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcl_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcl_user FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE stock_alerts (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    barang_id       BIGINT UNSIGNED NOT NULL,
    barang_masuk_id BIGINT UNSIGNED NULL,
    alert_type      ENUM('STOK_RENDAH','STOK_HABIS','MENDEKATI_EXP','KEDALUWARSA') NOT NULL,
    severity        ENUM('RENDAH','SEDANG','TINGGI','KRITIS') NOT NULL DEFAULT 'SEDANG',
    judul           VARCHAR(255) NOT NULL,
    pesan           TEXT NOT NULL,
    stok_saat_itu   INT NULL,
    nilai_ambang    INT NULL,
    tanggal_exp     DATE NULL,
    is_resolved     TINYINT(1) NOT NULL DEFAULT 0,
    resolved_at     DATETIME NULL,
    resolved_by     BIGINT UNSIGNED NULL,
    catatan_resolusi TEXT NULL,
    created_at      TIMESTAMP NULL,
    updated_at      TIMESTAMP NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_alert_terbuka (barang_id, barang_masuk_id, alert_type, is_resolved),
    KEY idx_alert_open (is_resolved, severity, created_at),
    CONSTRAINT fk_alert_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_bm FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_user FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE no_transaksi_seq (
    id          TINYINT UNSIGNED NOT NULL DEFAULT 1,
    last_number BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at  TIMESTAMP NULL,
    PRIMARY KEY (id),
    CONSTRAINT chk_seq_single_row CHECK (id = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO no_transaksi_seq (id, last_number) VALUES (1, 0);

CREATE TABLE audit_logs (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id      BIGINT UNSIGNED NULL,
    aksi         VARCHAR(80) NOT NULL,
    entity_type  VARCHAR(50) NOT NULL,
    entity_id    BIGINT UNSIGNED NULL,
    ringkasan    VARCHAR(255) NULL,
    data_sebelum JSON NULL,
    data_sesudah JSON NULL,
    ip_address   VARCHAR(45) NULL,
    request_id   CHAR(36) NULL,
    created_at   DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY idx_audit_entity (entity_type, entity_id, created_at),
    KEY idx_audit_user (user_id, created_at),
    KEY idx_audit_aksi (aksi, created_at),
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
