CREATE TABLE IF NOT EXISTS idempotency_keys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope         VARCHAR(64) NOT NULL,
    idem_key      VARCHAR(128) NOT NULL,
    user_id       BIGINT NOT NULL,
    resource_id   BIGINT NULL,
    request_hash  CHAR(64) NOT NULL,
    response_json JSONB NOT NULL,
    status_code   INT NOT NULL DEFAULT 200,
    created_at    TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT uq_idempotency_scope_user_key UNIQUE (scope, user_id, idem_key),
    CONSTRAINT fk_idempotency_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_idempotency_created ON idempotency_keys (created_at);
