-- Skema domain PKB Web (PostgreSQL)

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    email_verified_at TIMESTAMPTZ NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(32) NOT NULL DEFAULT 'sales',
    no_hp           VARCHAR(30) NULL,
    no_ktp          VARCHAR(32) NULL,
    alamat          TEXT NULL,
    jenis_kelamin   VARCHAR(1) NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NULL,
    updated_at      TIMESTAMPTZ NULL,
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT uq_users_no_ktp UNIQUE (no_ktp),
    CONSTRAINT chk_users_role CHECK (role IN ('super_admin','admin','afiliasi','sales')),
    CONSTRAINT chk_users_jk CHECK (jenis_kelamin IS NULL OR jenis_kelamin IN ('L','P'))
);
CREATE INDEX idx_users_role_active ON users (role, is_active);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    token_hash  CHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ NULL,
    user_agent  VARCHAR(255) NULL,
    ip_address  VARCHAR(45) NULL,
    created_at  TIMESTAMPTZ NULL,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_refresh_user_expired ON refresh_tokens (user_id, expires_at);

CREATE TABLE barang (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_barang     VARCHAR(64) NOT NULL,
    nama_item       VARCHAR(255) NOT NULL,
    brand           VARCHAR(100) NOT NULL,
    satuan          VARCHAR(20) NOT NULL DEFAULT 'PCS',
    stok_tersedia   INT NOT NULL DEFAULT 0,
    min_stock       INT NOT NULL DEFAULT 0,
    reorder_point   INT NOT NULL DEFAULT 0,
    metode_alokasi  VARCHAR(8) NOT NULL DEFAULT 'FEFO',
    expiry_alert_days INT NOT NULL DEFAULT 30,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NULL,
    updated_at      TIMESTAMPTZ NULL,
    CONSTRAINT uq_barang_kode UNIQUE (kode_barang),
    CONSTRAINT chk_barang_metode CHECK (metode_alokasi IN ('FEFO','FIFO'))
);
CREATE INDEX idx_barang_brand ON barang (brand);
CREATE INDEX idx_barang_active_stok ON barang (is_active, stok_tersedia);
CREATE INDEX idx_barang_nama ON barang (nama_item);

CREATE TABLE pelanggan (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_pelanggan            VARCHAR(32) NOT NULL,
    nama_pelanggan            VARCHAR(255) NOT NULL,
    tgl_registrasi            DATE NOT NULL,
    phone                     VARCHAR(30) NOT NULL,
    npwp_nik                  VARCHAR(32) NULL,
    nama_pemilik_npwp_nik     VARCHAR(255) NULL,
    alamat_npwp_nik           TEXT NULL,
    territory                 VARCHAR(100) NOT NULL,
    distrik                   VARCHAR(100) NOT NULL,
    alamat_toko               TEXT NOT NULL,
    rt_rw                     VARCHAR(20) NULL,
    provinsi                  VARCHAR(100) NOT NULL,
    kabupaten                 VARCHAR(100) NOT NULL,
    kecamatan                 VARCHAR(100) NOT NULL,
    kelurahan                 VARCHAR(100) NOT NULL,
    kode_pos                  VARCHAR(10) NULL,
    channel_outlet            VARCHAR(40) NOT NULL,
    alamat_pengantaran_barang TEXT NULL,
    jenis_bangunan            VARCHAR(50) NULL,
    status_bangunan           VARCHAR(50) NULL,
    nominal_pengambilan_pertama DECIMAL(15,2) NOT NULL DEFAULT 0,
    estimasi_batas_kredit     DECIMAL(15,2) NOT NULL DEFAULT 0,
    is_active                 BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                TIMESTAMPTZ NULL,
    updated_at                TIMESTAMPTZ NULL,
    CONSTRAINT uq_pelanggan_kode UNIQUE (kode_pelanggan),
    CONSTRAINT chk_pelanggan_channel CHECK (channel_outlet IN (
        'Modern Trade','Modern Trade Independent','General Trade','General Trade Kosmetik','Sub Agen'
    ))
);
CREATE INDEX idx_pelanggan_channel ON pelanggan (channel_outlet);
CREATE INDEX idx_pelanggan_wilayah ON pelanggan (territory, distrik);
CREATE INDEX idx_pelanggan_nama ON pelanggan (nama_pelanggan);

CREATE TABLE barang_masuk (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barang_id         BIGINT NOT NULL,
    no_faktur         VARCHAR(100) NOT NULL,
    no_batch          VARCHAR(100) NOT NULL,
    exp               DATE NOT NULL,
    tanggal_masuk     DATE NOT NULL,
    qty               INT NOT NULL,
    harga             DECIMAL(15,2) NOT NULL,
    disc_hpp_1        DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc_hpp_2        DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc_hpp_3        DECIMAL(5,2) NOT NULL DEFAULT 0,
    hpp               DECIMAL(15,2) NOT NULL DEFAULT 0,
    hpp_dengan_ppn    DECIMAL(15,2) NOT NULL DEFAULT 0,
    markup_mt_type    VARCHAR(16) NOT NULL DEFAULT 'percent',
    markup_mt_amount  DECIMAL(15,2) NOT NULL DEFAULT 0,
    markup_gt_type    VARCHAR(16) NOT NULL DEFAULT 'percent',
    markup_gt_amount  DECIMAL(15,2) NOT NULL DEFAULT 0,
    harga_mt          DECIMAL(15,2) NOT NULL DEFAULT 0,
    harga_gt          DECIMAL(15,2) NOT NULL DEFAULT 0,
    aging_month       INT NOT NULL DEFAULT 0,
    created_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NULL,
    updated_at        TIMESTAMPTZ NULL,
    CONSTRAINT uq_bm_batch UNIQUE (barang_id, no_batch, no_faktur),
    CONSTRAINT fk_bm_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_bm_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_bm_qty CHECK (qty > 0),
    CONSTRAINT chk_bm_disc CHECK (
        disc_hpp_1 BETWEEN 0 AND 100 AND
        disc_hpp_2 BETWEEN 0 AND 100 AND
        disc_hpp_3 BETWEEN 0 AND 100
    ),
    CONSTRAINT chk_bm_markup CHECK (
        markup_mt_type IN ('percent','value') AND markup_gt_type IN ('percent','value')
    )
);
CREATE INDEX idx_bm_barang_exp ON barang_masuk (barang_id, exp);
CREATE INDEX idx_bm_tanggal ON barang_masuk (tanggal_masuk);
CREATE INDEX idx_bm_faktur ON barang_masuk (no_faktur);

CREATE TABLE stock_movements (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barang_id         BIGINT NOT NULL,
    barang_masuk_id   BIGINT NULL,
    movement_type     VARCHAR(20) NOT NULL,
    qty               INT NOT NULL,
    saldo_setelah     INT NOT NULL,
    reference_type    VARCHAR(50) NULL,
    reference_id      BIGINT NULL,
    reference_no      VARCHAR(100) NULL,
    keterangan        TEXT NULL,
    created_by        BIGINT NULL,
    created_at        TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT fk_sm_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sm_batch FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE RESTRICT,
    CONSTRAINT fk_sm_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_sm_qty CHECK (qty <> 0),
    CONSTRAINT chk_sm_type CHECK (movement_type IN ('PENERIMAAN','PENJUALAN','PEMBATALAN','PENYESUAIAN','OPNAME'))
);
CREATE INDEX idx_sm_barang_created ON stock_movements (barang_id, created_at);
CREATE INDEX idx_sm_batch ON stock_movements (barang_masuk_id);
CREATE INDEX idx_sm_reference ON stock_movements (reference_type, reference_id);
CREATE INDEX idx_sm_type_created ON stock_movements (movement_type, created_at);

CREATE TABLE promos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_promo          VARCHAR(64) NOT NULL,
    nama_promo          VARCHAR(255) NOT NULL,
    deskripsi           TEXT NULL,
    tipe_promo          VARCHAR(32) NOT NULL,
    buy_qty             INT NULL,
    get_qty             INT NULL,
    bonus_qty           INT NOT NULL DEFAULT 0,
    discount_percentage DECIMAL(5,2) NOT NULL DEFAULT 0,
    discount_amount     DECIMAL(15,2) NOT NULL DEFAULT 0,
    min_qty             INT NOT NULL DEFAULT 1,
    min_amount          DECIMAL(15,2) NOT NULL DEFAULT 0,
    max_applications    INT NULL,
    kode_barang         VARCHAR(64) NULL,
    tanggal_mulai       DATE NOT NULL,
    tanggal_berakhir    DATE NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    syarat_ketentuan    TEXT NULL,
    created_by          BIGINT NULL,
    created_at          TIMESTAMPTZ NULL,
    updated_at          TIMESTAMPTZ NULL,
    CONSTRAINT uq_promo_kode UNIQUE (kode_promo),
    CONSTRAINT fk_promo_barang FOREIGN KEY (kode_barang) REFERENCES barang(kode_barang) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_promo_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_promo_periode CHECK (tanggal_berakhir >= tanggal_mulai),
    CONSTRAINT chk_promo_tipe CHECK (tipe_promo IN ('buy_x_get_y','bonus_qty','percentage_discount','fixed_discount')),
    CONSTRAINT chk_promo_bxgy CHECK (
        tipe_promo <> 'buy_x_get_y'
        OR (buy_qty IS NOT NULL AND buy_qty > 0 AND get_qty IS NOT NULL AND get_qty > 0)
    )
);
CREATE INDEX idx_promo_aktif ON promos (is_active, tanggal_mulai, tanggal_berakhir);
CREATE INDEX idx_promo_barang ON promos (kode_barang);

CREATE TABLE transaksi_penjualan (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_transaksi      VARCHAR(32) NULL,
    tanggal           DATE NOT NULL,
    periode           CHAR(7) NOT NULL,
    kode_pelanggan    VARCHAR(32) NOT NULL,
    nama_pelanggan    VARCHAR(255) NOT NULL,
    alamat            TEXT NOT NULL,
    channel_outlet    VARCHAR(50) NOT NULL,
    area              VARCHAR(100) NOT NULL,
    is_multi_item     BOOLEAN NOT NULL DEFAULT TRUE,
    disc1_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc2_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc3_persen      DECIMAL(5,2) NOT NULL DEFAULT 0,
    ppn_persen        DECIMAL(5,2) NOT NULL DEFAULT 11,
    total             DECIMAL(15,2) NOT NULL DEFAULT 0,
    ppn_nominal       DECIMAL(15,2) NOT NULL DEFAULT 0,
    total_akhir       DECIMAL(15,2) NOT NULL DEFAULT 0,
    jumlah_item       INT NOT NULL DEFAULT 0,
    total_qty_ditagih INT NOT NULL DEFAULT 0,
    total_qty_keluar  INT NOT NULL DEFAULT 0,
    status_approval   VARCHAR(16) NOT NULL DEFAULT 'pending',
    approved_at       TIMESTAMPTZ NULL,
    approved_by       BIGINT NULL,
    approval_notes    TEXT NULL,
    fulfillment_status VARCHAR(32) NOT NULL DEFAULT 'awaiting_approval',
    qty_fulfilled     INT NOT NULL DEFAULT 0,
    qty_backorder     INT NOT NULL DEFAULT 0,
    stock_notes       TEXT NULL,
    status_pembayaran VARCHAR(16) NOT NULL DEFAULT 'hutang',
    jumlah_dibayar    DECIMAL(15,2) NOT NULL DEFAULT 0,
    sisa_hutang       DECIMAL(15,2) NOT NULL DEFAULT 0,
    tanggal_jatuh_tempo DATE NULL,
    tanggal_pembayaran_terakhir TIMESTAMPTZ NULL,
    keterangan_pembayaran TEXT NULL,
    faktur_dicetak_at TIMESTAMPTZ NULL,
    faktur_dicetak_by BIGINT NULL,
    sales_id          BIGINT NULL,
    created_at        TIMESTAMPTZ NULL,
    updated_at        TIMESTAMPTZ NULL,
    CONSTRAINT uq_tp_no_transaksi UNIQUE (no_transaksi),
    CONSTRAINT fk_tp_pelanggan FOREIGN KEY (kode_pelanggan) REFERENCES pelanggan(kode_pelanggan) ON UPDATE CASCADE,
    CONSTRAINT fk_tp_sales FOREIGN KEY (sales_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_tp_approver FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_tp_status CHECK (status_approval IN ('pending','approved','rejected')),
    CONSTRAINT chk_tp_fulfillment CHECK (fulfillment_status IN ('awaiting_approval','full','partial','backorder','stock_shortage')),
    CONSTRAINT chk_tp_bayar_status CHECK (status_pembayaran IN ('lunas','hutang','sebagian')),
    CONSTRAINT chk_tp_bayar CHECK (
        ABS(jumlah_dibayar + sisa_hutang - total_akhir) < 0.01
    ),
    CONSTRAINT chk_tp_approved CHECK (
        (status_approval = 'approved' AND no_transaksi IS NOT NULL AND approved_at IS NOT NULL)
        OR status_approval <> 'approved'
    )
);
CREATE INDEX idx_tp_status_tanggal ON transaksi_penjualan (status_approval, tanggal);
CREATE INDEX idx_tp_pelanggan ON transaksi_penjualan (kode_pelanggan);
CREATE INDEX idx_tp_sales_tanggal ON transaksi_penjualan (sales_id, tanggal);
CREATE INDEX idx_tp_bayar ON transaksi_penjualan (status_pembayaran, tanggal_jatuh_tempo);
CREATE INDEX idx_tp_periode ON transaksi_penjualan (periode);
CREATE INDEX idx_tp_channel ON transaksi_penjualan (channel_outlet);

CREATE TABLE transaksi_detail (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_penjualan_id BIGINT NOT NULL,
    urutan                SMALLINT NOT NULL DEFAULT 1,
    kode_item             VARCHAR(64) NOT NULL,
    nama_item             VARCHAR(255) NOT NULL,
    satuan                VARCHAR(20) NOT NULL,
    barang_masuk_id       BIGINT NULL,
    batch_number          VARCHAR(100) NULL,
    expiry_date           DATE NULL,
    qty                   INT NOT NULL,
    qty_promo             INT NOT NULL DEFAULT 0,
    total_qty_keluar      INT NOT NULL DEFAULT 0,
    harga                 DECIMAL(15,2) NOT NULL,
    subtotal              DECIMAL(15,2) NOT NULL,
    disc1_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc2_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    disc3_persen          DECIMAL(5,2) NOT NULL DEFAULT 0,
    total_after_disc      DECIMAL(15,2) NOT NULL,
    hpp_snapshot          DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NULL,
    updated_at            TIMESTAMPTZ NULL,
    CONSTRAINT uq_td_urutan UNIQUE (transaksi_penjualan_id, urutan),
    CONSTRAINT fk_td_transaksi FOREIGN KEY (transaksi_penjualan_id) REFERENCES transaksi_penjualan(id) ON DELETE CASCADE,
    CONSTRAINT fk_td_barang FOREIGN KEY (kode_item) REFERENCES barang(kode_barang) ON UPDATE CASCADE,
    CONSTRAINT fk_td_batch FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE RESTRICT,
    CONSTRAINT chk_td_qty CHECK (qty > 0 AND qty_promo >= 0),
    CONSTRAINT chk_td_qty_keluar CHECK (total_qty_keluar = qty + qty_promo)
);
CREATE INDEX idx_td_transaksi ON transaksi_detail (transaksi_penjualan_id);
CREATE INDEX idx_td_item ON transaksi_detail (kode_item);
CREATE INDEX idx_td_batch ON transaksi_detail (barang_masuk_id);

CREATE TABLE transaksi_detail_promo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_detail_id BIGINT NOT NULL,
    promo_id            BIGINT NOT NULL,
    kode_promo          VARCHAR(64) NOT NULL,
    nama_promo          VARCHAR(255) NOT NULL,
    tipe_promo          VARCHAR(32) NOT NULL,
    qty_bonus           INT NOT NULL DEFAULT 0,
    nilai_diskon        DECIMAL(15,2) NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NULL,
    CONSTRAINT fk_tdp_detail FOREIGN KEY (transaksi_detail_id) REFERENCES transaksi_detail(id) ON DELETE CASCADE,
    CONSTRAINT fk_tdp_promo FOREIGN KEY (promo_id) REFERENCES promos(id) ON DELETE RESTRICT,
    CONSTRAINT chk_tdp_tipe CHECK (tipe_promo IN ('buy_x_get_y','bonus_qty','percentage_discount','fixed_discount'))
);
CREATE INDEX idx_tdp_detail ON transaksi_detail_promo (transaksi_detail_id);
CREATE INDEX idx_tdp_promo ON transaksi_detail_promo (promo_id);

CREATE TABLE riwayat_pembayaran (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaksi_penjualan_id BIGINT NOT NULL,
    old_jumlah_dibayar DECIMAL(15,2) NOT NULL DEFAULT 0,
    new_jumlah_dibayar DECIMAL(15,2) NOT NULL DEFAULT 0,
    old_sisa_hutang    DECIMAL(15,2) NOT NULL DEFAULT 0,
    new_sisa_hutang    DECIMAL(15,2) NOT NULL DEFAULT 0,
    old_status         VARCHAR(16) NULL,
    new_status         VARCHAR(16) NULL,
    nominal_pembayaran DECIMAL(15,2) NOT NULL DEFAULT 0,
    metode_pembayaran  VARCHAR(50) NULL,
    tanggal_pembayaran DATE NULL,
    keterangan         TEXT NULL,
    changed_by         BIGINT NULL,
    changed_at         TIMESTAMPTZ(3) NOT NULL,
    created_at         TIMESTAMPTZ NULL,
    CONSTRAINT fk_rp_transaksi FOREIGN KEY (transaksi_penjualan_id) REFERENCES transaksi_penjualan(id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_user FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_rp_old_status CHECK (old_status IS NULL OR old_status IN ('lunas','hutang','sebagian')),
    CONSTRAINT chk_rp_new_status CHECK (new_status IS NULL OR new_status IN ('lunas','hutang','sebagian'))
);
CREATE INDEX idx_rp_transaksi ON riwayat_pembayaran (transaksi_penjualan_id, changed_at);
CREATE INDEX idx_rp_tanggal ON riwayat_pembayaran (tanggal_pembayaran);

CREATE TABLE price_change_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barang_masuk_id   BIGINT NOT NULL,
    barang_id         BIGINT NOT NULL,
    bulk_operation_id CHAR(36) NOT NULL,
    old_harga         DECIMAL(15,2) NULL,
    old_disc_hpp_1    DECIMAL(5,2) NULL,
    old_disc_hpp_2    DECIMAL(5,2) NULL,
    old_disc_hpp_3    DECIMAL(5,2) NULL,
    old_markup_mt_type   VARCHAR(16) NULL,
    old_markup_mt_amount DECIMAL(15,2) NULL,
    old_markup_gt_type   VARCHAR(16) NULL,
    old_markup_gt_amount DECIMAL(15,2) NULL,
    old_harga_mt      DECIMAL(15,2) NULL,
    old_harga_gt      DECIMAL(15,2) NULL,
    old_hpp           DECIMAL(15,2) NULL,
    new_harga         DECIMAL(15,2) NULL,
    new_disc_hpp_1    DECIMAL(5,2) NULL,
    new_disc_hpp_2    DECIMAL(5,2) NULL,
    new_disc_hpp_3    DECIMAL(5,2) NULL,
    new_markup_mt_type   VARCHAR(16) NULL,
    new_markup_mt_amount DECIMAL(15,2) NULL,
    new_markup_gt_type   VARCHAR(16) NULL,
    new_markup_gt_amount DECIMAL(15,2) NULL,
    new_harga_mt      DECIMAL(15,2) NULL,
    new_harga_gt      DECIMAL(15,2) NULL,
    new_hpp           DECIMAL(15,2) NULL,
    keterangan        TEXT NULL,
    changed_by        BIGINT NULL,
    changed_at        TIMESTAMPTZ(3) NOT NULL,
    created_at        TIMESTAMPTZ NULL,
    CONSTRAINT fk_pcl_bm FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcl_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_pcl_user FOREIGN KEY (changed_by) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_pcl_barang ON price_change_logs (barang_id, changed_at);
CREATE INDEX idx_pcl_bulk ON price_change_logs (bulk_operation_id);
CREATE INDEX idx_pcl_bm ON price_change_logs (barang_masuk_id);

CREATE TABLE stock_alerts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barang_id       BIGINT NOT NULL,
    barang_masuk_id BIGINT NULL,
    alert_type      VARCHAR(20) NOT NULL,
    severity        VARCHAR(16) NOT NULL DEFAULT 'SEDANG',
    judul           VARCHAR(255) NOT NULL,
    pesan           TEXT NOT NULL,
    stok_saat_itu   INT NULL,
    nilai_ambang    INT NULL,
    tanggal_exp     DATE NULL,
    is_resolved     BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at     TIMESTAMPTZ NULL,
    resolved_by     BIGINT NULL,
    catatan_resolusi TEXT NULL,
    created_at      TIMESTAMPTZ NULL,
    updated_at      TIMESTAMPTZ NULL,
    CONSTRAINT uq_alert_terbuka UNIQUE (barang_id, barang_masuk_id, alert_type, is_resolved),
    CONSTRAINT fk_alert_barang FOREIGN KEY (barang_id) REFERENCES barang(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_bm FOREIGN KEY (barang_masuk_id) REFERENCES barang_masuk(id) ON DELETE CASCADE,
    CONSTRAINT fk_alert_user FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_alert_type CHECK (alert_type IN ('STOK_RENDAH','STOK_HABIS','MENDEKATI_EXP','KEDALUWARSA')),
    CONSTRAINT chk_alert_severity CHECK (severity IN ('RENDAH','SEDANG','TINGGI','KRITIS'))
);
CREATE INDEX idx_alert_open ON stock_alerts (is_resolved, severity, created_at);

CREATE TABLE no_transaksi_seq (
    id          SMALLINT NOT NULL DEFAULT 1 PRIMARY KEY,
    last_number BIGINT NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ NULL,
    CONSTRAINT chk_seq_single_row CHECK (id = 1)
);

INSERT INTO no_transaksi_seq (id, last_number) VALUES (1, 0);

CREATE TABLE audit_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NULL,
    aksi         VARCHAR(80) NOT NULL,
    entity_type  VARCHAR(50) NOT NULL,
    entity_id    BIGINT NULL,
    ringkasan    VARCHAR(255) NULL,
    data_sebelum JSONB NULL,
    data_sesudah JSONB NULL,
    ip_address   VARCHAR(45) NULL,
    request_id   CHAR(36) NULL,
    created_at   TIMESTAMPTZ(3) NOT NULL,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id, created_at);
CREATE INDEX idx_audit_user ON audit_logs (user_id, created_at);
CREATE INDEX idx_audit_aksi ON audit_logs (aksi, created_at);
